#!/usr/bin/env bash
set -e
set -o pipefail
set -u

main() {
  # Pass through require plugin properties:
  export GALLERY_BUCKET_NAME="$BUILDKITE_PLUGIN_SCREENSHOT_GALLERY_BUCKET_NAME"
  export CANONICAL_REPO_AND_BRANCH="$BUILDKITE_PLUGIN_SCREENSHOT_GALLERY_CANONICAL_REPO_AND_BRANCH"
  export BUILDKITE_GITHUB_ORG="$BUILDKITE_PLUGIN_SCREENSHOT_GALLERY_GITHUB_ORG"
  export BUILDKITE_GITHUB_REPO="$BUILDKITE_PLUGIN_SCREENSHOT_GALLERY_GITHUB_REPO"

  # ... and the optional ones:
  export SCREENSHOT_PATTERN="${BUILDKITE_PLUGIN_SCREENSHOT_GALLERY_SCREENSHOT_PATTERN:-}"

  local script_dir; script_dir=$(unset CDPATH && cd "$(dirname "$BASH_SOURCE")" && pwd)
  local repo_dir; repo_dir=$(unset CDPATH && cd "${script_dir}/.." && pwd)

  if [ -z "${AWS_ACCESS_KEY_ID:-}" ]; then
    cat <<EOF
      Couldn't find AWS_... environment variables, and so can't upload anything to S3!

      You're likely using this plugin without the culturamp/aws-assume-role plugin;
      make sure your publish step looks like this:

      - name: "Publish the screenshot gallery"
        plugins:
          - cultureamp/aws-assume-role#v0.1.0:
              role: "arn:aws:iam::123456789012:role/example/build/role/for/uploading"
          - cultureamp/screenshot-gallery:
              canonical_repo_and_branch: "murmur/master"
              bucket_name: "example-screenshot-gallery"
              github_org: "cultureamp"
              github_repo: "example-repo"
              screenshot_pattern: "screenshot_*.png"
        # ... and other config fields as usual, eg. agents.
EOF
    exit 1
  fi

  cd "${repo_dir}"
  "${repo_dir}/gallery/create_gallery.sh"
}

main
